Compose TiltSeries streaming
scipion-em/scipion-em-tomo pull request #248
Opened 2022-10-03 11:16 UTC by albertmena

Behavior:

When a tilt Serie is acquired and there are all the micrographs in the input set, a stack is generated and added the tilt serie to the set of tilt series in the output.

Input: 

- set of micrographs (from alignment protocol...)
- folder with mdoc files with all the tilts

Times out:

- Time for the next tilt (if the tiltserie acquisition has not ended and there is a mdoc file with information of the tilts acquired). 
- Time next micrograph: Time to wait until the next micrograph is processed by the previous protocol (alignment)
- Time next TiltSerie: Time to wait until the next TiltSerie starts to be acquired (time until the mdoc file is created)

2022-10-03 14:50 UTC, azazellochg commented
Hi, I didnt get where the micrographs are coming from? motion correction protocols produce outputTiltSeries. Or you are referring to acquisition in serialem which generates (usually binned) TS mrc stacks? But then you will have 1 mdoc file for each stack.

2022-10-03 16:51 UTC, pconesa commented
We are feeding this protocol with SPA motion correction micrographs.

El lun., 3 oct. 2022 16:50, Grigory Sharov ***@***.***>
escribió:

> Hi, I didnt get where the micrographs are coming from? motion correction
> protocols produce outputTiltSeries. Or you are referring to acquisition in
> serialem which generates (usually binned) TS mrc stacks? But then you will
> have 1 mdoc file for each stack.
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/scipion-em/scipion-em-tomo/pull/248#issuecomment-1265583695>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AAF7ZYI4N5AF2Z7ZYOEYLQDWBLXEBANCNFSM6AAAAAAQ3PXMJI>
> .
> You are receiving this because your review was requested.Message ID:
> ***@***.***>
>

2022-10-03 17:56 UTC, azazellochg commented
O_o

Ehm, okay.

On Mon, Oct 3, 2022, 17:51 Pablo Conesa ***@***.***> wrote:

> We are feeding this protocol with SPA motion correction micrographs.
>
> El lun., 3 oct. 2022 16:50, Grigory Sharov ***@***.***>
> escribió:
>
> > Hi, I didnt get where the micrographs are coming from? motion correction
> > protocols produce outputTiltSeries. Or you are referring to acquisition
> in
> > serialem which generates (usually binned) TS mrc stacks? But then you
> will
> > have 1 mdoc file for each stack.
> >
> > —
> > Reply to this email directly, view it on GitHub
> > <
> https://github.com/scipion-em/scipion-em-tomo/pull/248#issuecomment-1265583695
> >,
> > or unsubscribe
> > <
> https://github.com/notifications/unsubscribe-auth/AAF7ZYI4N5AF2Z7ZYOEYLQDWBLXEBANCNFSM6AAAAAAQ3PXMJI
> >
> > .
> > You are receiving this because your review was requested.Message ID:
> > ***@***.***>
> >
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/scipion-em/scipion-em-tomo/pull/248#issuecomment-1265746064>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/ABVBPJU3MNPZU5QYI3OAGTDWBMFKHANCNFSM6AAAAAAQ3PXMJI>
> .
> You are receiving this because you commented.Message ID:
> ***@***.***>
>

2022-10-04 15:23 UTC, azazellochg commented
I would then add a point that serialem can rearrange binned TS stacks and mdocs after the tilt-series is collected (https://github.com/scipion-em/scipion-em-tomo/issues/232). I hope this will be supported here as well.

2022-10-04 15:28 UTC, pconesa commented
Are talking about 2 options here:

1.- Serial EM does nothing, so MC is done in "Scipion" and TS compose is done on a "non rearranged mdoc"
2.- Serial EM does the rearrange, and I guess the MC too and the stack? So we just register the whole Tilt series?

2022-10-04 15:35 UTC, azazellochg commented
serialem does not re-arrange movies in any way since they are individual files, so mc is not affected. I suppose the composition will depend on how you get the info from the mdoc. Are you comparing micname from scipion with movie file name in mdoc?

2022-10-04 15:40 UTC, pconesa requested changes
Almost there. Please, could you provide comments at least on the methods that are more complex. I mean doc strings.

And a test.

2022-10-04 15:40 UTC, pconesa commented on tomo/protocols/protocol_compose_TS.py
> +    def readMdoc(self, list_remains):
I think it will be better to deal with a single mdoc in this step. For resuming options is better.

2022-10-04 15:48 UTC, pconesa commented
We do the matching by name in mdoc with the "movie/mic name". So I guess we are covered if is just the mdoc what is rearranged.

2022-10-05 07:58 UTC, azazellochg commented
will this support pacetomo (https://github.com/scipion-em/scipion-em-tomo/issues/236)?

2022-10-05 11:47 UTC, pconesa commented
Does pacetomo generate mdoc files like serial EM?

2022-10-11 08:37 UTC, albertmena commented
The test is pending to do

2022-10-28 07:08 UTC, pconesa approved these changes

2022-10-28 07:09 UTC, merged