accepting dose accumulation in the tlt file
scipion-em/scipion-em-tomo pull request #316
Opened 2023-02-05 21:08 UTC by MohamadHarastani

In this PR I added the option (does not impact previous usage) to import the accumulated dose of a tilt series as a second column in the tlt/rawtlt file.
This is not a new practice, it is already allowed in the same way in aretomo (see manual section Dose Weighting).

2023-02-06 13:00 UTC, pconesa requested changes
Nice, it is always good to be flexible when importing. Good job!

Could you also please add a line  in the CHANGES.txt plesase.

2023-02-06 13:00 UTC, pconesa commented on tomo/protocols/protocol_ts_import.py
> +                                tltFn = os.path.splitext(imageFile)[0] + '.tlt'
NIce, It would be nice to "extract" these 6 lines of code that are similar to those below (line 764) to a method and use it from both places.

2023-02-06 19:17 UTC, MohamadHarastani commented
Hello Pablo
I am traveling and will be back in a week. If you can do what you asked me
in the meantime it will be appreciated, otherwise I will do it when I am
back.
Cheers
Mohamad

On Mon, Feb 6, 2023, 2:00 PM Pablo Conesa ***@***.***> wrote:

> ***@***.**** requested changes on this pull request.
>
> Nice, it is always good to be flexible when importing. Good job!
>
> Could you also please add a line in the CHANGES.txt plesase.
> ------------------------------
>
> In tomo/protocols/protocol_ts_import.py
> <https://github.com/scipion-em/scipion-em-tomo/pull/316#discussion_r1097346279>
> :
>
> >                              dosePerFrame = self.dosePerFrame.get()
> -                            accumDose = \
> -                                self.dosePerFrame.get() * \
> -                                int(to if min(toList) == 1 else (int(to) + 1))
> +                            doses = []
> +                            anglesFrom = self.getEnumText('anglesFrom')
> +                            if anglesFrom == self.ANGLES_FROM_TLT:
> +                                tltFn = os.path.splitext(imageFile)[0] + '.tlt'
>
> NIce, It would be nice to "extract" these 6 lines of code that are similar
> to those below (line 764) to a method and use it from both places.
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/scipion-em/scipion-em-tomo/pull/316#pullrequestreview-1285143570>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AK2I5FMEJAYIMJKP7JC5RQDWWDYWTANCNFSM6AAAAAAUR7NDTU>
> .
> You are receiving this because you authored the thread.Message ID:
> ***@***.***>
>

2023-02-10 11:20 UTC, pconesa commented
Hi, I'd do it but since you are pushing from your fork, I'd need to clone yours and so on. I'll wait. Next time do not us a fork, just create a branch here.

2023-02-10 11:23 UTC, pconesa commented
I don know why you weren't already a member of scipion-em. You got an invitation!!

2023-02-16 15:03 UTC, MohamadHarastani commented on tomo/protocols/protocol_ts_import.py
> +                                tltFn = os.path.splitext(imageFile)[0] + '.tlt'
Done

2023-02-16 15:06 UTC, MohamadHarastani commented
Sorry for the delay, I went to disneyland :-)

2023-02-17 09:03 UTC, pconesa commented
Disneyland justifies it! ;-)

2023-02-17 09:04 UTC, pconesa commented on CHANGES.txt
> +- Added an option to import the dose accumulation using a tlt file as second column
nice micro version jump!

2023-02-23 15:28 UTC, pconesa approved these changes

2023-02-23 15:29 UTC, merged