Fi improve ts assign tm
scipion-em/scipion-em-tomo pull request #400
Opened 2023-09-21 13:41 UTC by fede-pe

This PR includes:

- Enhancement of tilt series assign alignment protocol

2023-09-26 13:46 UTC, pconesa commented on tomo/protocols/protocol_assignTransformationTS.py
> +                      params.EnumParam,
For this there are boolean params that are more convenient

2023-09-26 13:47 UTC, pconesa commented on tomo/protocols/protocol_assignTransformationTS.py
> +                           'this will be combined with the ')
with the ..? suspense .. wait for the next release.. ;-)

2023-09-26 13:50 UTC, pconesa requested changes
Just some minor changes.

2023-09-27 13:46 UTC, fede-pe commented on tomo/protocols/protocol_assignTransformationTS.py
> +                      params.EnumParam,
Fixed

2023-09-27 13:47 UTC, fede-pe commented on tomo/protocols/protocol_assignTransformationTS.py
> +                           'this will be combined with the ')
I was planning a premium feature... but you have a point :)

2023-09-27 13:56 UTC, fede-pe commented on tomo/protocols/protocol_assignTransformationTS.py
> +        for tsGetTM in self.getTMSetOfTiltSeries.get():
Fixed!!

2023-10-02 09:28 UTC, pconesa approved these changes

2023-10-02 09:28 UTC, merged

2023-10-02 09:51 UTC, azazellochg commented on tomo/protocols/protocol_assignTransformationTS.py
> +                           'alignment, both precious and new alignment are combined.')
precios : )