Re stack excluded views
scipion-em/scipion-em-tomo pull request #505
Opened 2024-07-31 11:14 UTC by fonsecareyna82

2024-08-04 11:36 UTC, azazellochg requested changes
![image](https://github.com/user-attachments/assets/54b420c0-40a5-4561-8917-f376a3301cf2)
the numbers do not match

2024-08-04 11:37 UTC, azazellochg commented
Also, if I open restacked TS with imod, it still shows a complete stack

2024-08-05 08:18 UTC, JorMaister commented
Hi, @azazellochg, the image posted above seems to be the result of a motion correction protocol. I haven't gone through it with the exclusion re-stacking. Did the code state that corresponds top the image above use this scipion-em-tomo branch in the current state?

2024-08-05 08:21 UTC, fonsecareyna82 commented
Yes @azazellochg , I have other changes where what you comment is solved. I will upload them today.

2024-08-05 14:12 UTC, fonsecareyna82 commented
To test this branch, we needs the "re_stack_images" branch of scipion-em.

2024-08-06 07:31 UTC, azazellochg commented
1) when pressing Save button I get:
```
Traceback (most recent call last):
File "/home/gsharov/soft/miniconda3/envs/scipion3/lib/python3.8/tkinter/__init__.py", line 1892, in __call__
return self.func(*args)
File "/home/gsharov/soft/scipion-em-plugins/scipion-em-tomo/tomo/viewers/views_tkinter_tree.py", line 488, in _saveExcluded
imageReader.write(stackImages, newBinaryName, sr=obj.getSamplingRate(), isStack=True)
File "/home/gsharov/soft/scipion3/scipion-em/pwem/viewers/mdviewer/readers.py", line 32, in write
imageReader.write(pilImages, fileName, sr, isStack)
File "/home/gsharov/soft/scipion3/scipion-em/pwem/emlib/image/image_readers.py", line 168, in write
stack = numpy.stack(pilImages, axis=0)
File "<__array_function__ internals>", line 200, in stack
File "/home/gsharov/soft/miniconda3/envs/scipion3/lib/python3.8/site-packages/numpy/core/shape_base.py", line 464, in stack
raise ValueError('all input arrays must have the same shape')
ValueError: all input arrays must have the same shape
```
2) help dialog text needs to be updated as some buttons were moved to the right

2024-08-06 07:39 UTC, azazellochg commented on tomo/viewers/views_tkinter_tree.py
> +                _, obj = self._provider.getTiltSerie(ts.getTsId())
ts.getTsId() should be saved into a var instead of calling it all the time

2024-08-06 07:40 UTC, azazellochg commented on tomo/viewers/views_tkinter_tree.py
> +                            newTi.setLocation(ti.getLocation())
copyInfo already saves location, no?

2024-08-06 07:52 UTC, azazellochg commented on tomo/viewers/views_tkinter_tree.py
> +                    newTs.write()
why this is required?

2024-08-06 10:33 UTC, fonsecareyna82 commented on tomo/viewers/views_tkinter_tree.py
> +                    newTs.write()
Is to ensure that all tiltimages have not been marked as excluded one by one and not from the checkbox of the tiltseries.

2024-08-06 10:34 UTC, azazellochg commented on tomo/viewers/views_tkinter_tree.py
> +                    newTs.write()
I mean newTs.write() - is this required? There's another write call for the set below

2024-08-06 10:40 UTC, fonsecareyna82 commented on tomo/viewers/views_tkinter_tree.py
> +                    newTs.write()
for some reason I was not saving the TS. That's why I forced to write them

2024-08-06 10:41 UTC, fonsecareyna82 commented on tomo/viewers/views_tkinter_tree.py
> +                    newTs.write()
but I can look at it in more depth

2024-08-08 07:36 UTC, azazellochg approved these changes

2024-08-08 10:21 UTC, azazellochg commented on tomo/viewers/views_tkinter_tree.py
>                   '2. Increase contrast button to enhance the tiltimage contrast.\n'
this button has been moved to the right, can you delete this?

2024-08-08 10:22 UTC, azazellochg commented on tomo/viewers/views_tkinter_tree.py
>                   '3. Save button to create a new set with excluded views marked.', self)
it does more than that now

2024-08-09 08:37 UTC, merged